version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    # network_mode: "host"
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090